name: ci

on:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      js: ${{ steps.changes.outputs.js }}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: .github/file-filters.yml
          base: ${{ contains(github.ref, 'master') && github.ref || contains(github.ref, 'release') && github.ref || contains(github.ref, 'patch') && github.ref || github.event.repository.default_branch }}

  js:
    if: needs.changes.outputs.js == 'true'
    needs: changes
    uses: ./.github/workflows/js.yml

  ts:
    if: needs.changes.outputs.ts == 'true'
    needs: changes
    uses: ./.github/workflows/ts.yml

  mix:
    if: needs.changes.outputs.js == 'true' || needs.changes.outputs.ts == 'true'
    needs: changes
    uses: ./.github/workflows/mix.yml

  status-check:
    if: ${{ !cancelled() }}
    needs: ["js", "ts", "mix"]
    runs-on: ubuntu-latest
    steps:
      - name: Check All Job Status
        id: status_check
        if: needs.js.result == 'failure' || needs.ts.result == 'failure' || needs.mix.result == 'failure'
        run: exit 1
      - name: Pass Status Check
        if: steps.status_check.conclusion == 'skipped'
        run: exit 0
