name: git-pr-release
on:
  pull_request:
    branches:
      - develop
      - patch
      - release
      - hotfix
    types: [closed]

jobs:
  git-pr-release:
    # 1. develop ブランチに patch ブランチ以外のブランチ（=バックポート）からPRがマージされた場合: develop to patch
    # 2. patch ブランチに release 以外のブランチ（=バックポート）からPRがマージされた場合: patch to release
    # 3. release ブランチに patch からPRがマージされた場合: release to main
    # 4. hotfix ブランチに PRがマージされた場合: hotfix to main
    if: github.event.pull_request.merged == true && (
      (github.base_ref == 'develop' && github.head_ref != 'patch') ||
      (github.base_ref == 'patch' && github.head_ref != 'release') ||
      (github.base_ref == 'release' && github.head_ref == 'patch') ||
      github.base_ref == 'hotfix'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: echo env
        run: |
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install git-pr-release
        run: gem install --no-document git-pr-release --version 2.2.0
      - name: Update git config
        run: git config --global --add safe.directory "$(pwd)"
      - name: Create PR
        run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.PAT }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{
            github.ref_name == 'develop' && 'patch' ||
            github.ref_name == 'patch' && 'release' ||
            github.ref_name == 'release' && 'main' ||
            github.ref_name == 'hotfix' && 'main'
            }}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ github.ref_name }}
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .github/PR_RELEASE_TEMPLATE.erb
