name: git-pr-release-backport
on:
  pull_request:
    branches:
      - main
      - patch
    types: [closed]

jobs:
  git-pr-release:
    if: ${{
      github.base_ref == 'main' && github.head_ref == 'release' ||
      github.base_ref == 'patch' && github.head_ref == 'release'
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install git-pr-release
        run: gem install --no-document git-pr-release --version 2.2.0
      - name: Update git config
        run: git config --global --add safe.directory "$(pwd)"
      - name: Create PR
        run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{
            (github.base_ref == 'main' && github.ref_name == 'release') && 'patch' ||
            (github.base_ref == 'patch' && github.ref_name == 'release') && 'develop'
            }}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{
            (github.base_ref == 'main' && github.ref_name == 'release') && 'release' ||
            (github.base_ref == 'patch' && github.ref_name == 'release') && 'patch'
            }}
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .github/PR_RELEASE_TEMPLATE_BACKPORT.erb
