name: Mix
on:
  workflow_call:
    inputs:
      activate-job:
        required: true
        type: boolean

jobs:
  js:
    if: inputs.activate-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.x, 12.x, 14.x]
    steps:
      - name: Run Mix
        run: echo "Hello JavaScript"
