name: Mix
on:
  workflow_call:

jobs:
  js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.x, 12.x, 14.x]
    steps:
      - name: Run Mix
        run: echo "Hello JavaScript"
