name: TypeScript
on:
  workflow_call:
    inputs:
      activate-job:
        required: true
        type: boolean

jobs:
  ts:
    if: inputs.activate-job
    runs-on: ubuntu-latest
    steps:
      - name: Run TypeScript
        run: echo "Hello TypeScript"
